### ISSUE TITLE
keytool error with fvconfig generate config.xml

### ISSUE THREAD

**Issue by 09bicsemalam** [opennetworkinglab/flowvisor#237]
Hi.

I was following the installation instruction in the flowvisor installation manual [1]. But when it comes to generating config.xml through fvconfig, it gives me the following error:

fvconfig generate /usr/local/etc/flowvisor/config.xml

Could not  find /usr/local/etc/flowvisor/envs.sh: dying...

I ensured the folder is accessible but again on running the above command, I got: 

netforall@netforall:~$ fvconfig generate /usr/local/etc/flowvisor/config.xml
Trying to generate SSL Server Key with passwd from scripts/envs.sh
Generating cert with common name == user
keytool error: java.lang.Exception: Key pair not generated, alias <mykey> already exists
Exception in thread "main" java.lang.NoClassDefFoundError: org/flowvisor/config/FVConfig
Caused by: java.lang.ClassNotFoundException: org.flowvisor.config.FVConfig
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: org.flowvisor.config.FVConfig. Program will exit.

---

Im using version FV-0.8

**Comment by 09bicsemalam** [comment]
[1]  https://github.com/OPENNETWORKINGLAB/flowvisor/wiki/Installation-from-Source

**Comment by alshabib** [comment]
It seems that the code is not compiled or that there were errors during code compilation. DId you manage to compile the code successfully?

**Comment by 09bicsemalam** [comment]
yes.. My build was unsuccessful.

It gives me error like: 

---

ant
Buildfile: /home/netforall/flowvisor/build.xml

init:

compile:
    [javac] /home/user/flowvisor/build.xml:60: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

dist:

BUILD FAILED
/home/netforall/flowvisor/build.xml:74: /home/netforall/flowvisor/dist/flowvisor.jar is read-only.

---

**Comment by mssumanth** [comment]
I believe the default permissions should have been correct.
But probably it has got changed somehow.
(as it is an older version which you are using, am not sure why)
I guess you have to change the permissions of flowvisor.jar
by using:
chmod 664 flowvisor.jar
(or something similar which gives you more than read permission)
and could you please try building again which should be successful and
then later try generating the config.xml.

Cheers
Sumanth

**Comment by 09bicsemalam** [comment]
I gave permissions to the flowvisor.jar file and had a successful built. 

I also installed it. I want to run flowvisor in the same user that I have used to install it. I didn't create another user(flowvisor) as it is stated in the installation manual. Is it possible this way?

**Comment by alshabib** [comment]
Sure that can work as well, but it is less secure.

Is your problem now fixed?

## 

Ali Al-Shabibi

On May 22, 2013, at 6:21, 09bicsemalam notifications@github.com wrote:

I gave permissions to the flowvisor.jar file and had a successful built.

I also installed it. I want to run flowvisor in the same user that I have
used to install it. I didn't create another user(flowvisor) as it is stated
in the installation manual. Is it possible this way?

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/237#issuecomment-18277659
.

**Comment by 09bicsemalam** [comment]
I have installed it but with an error. When I start FV. a message appears:

Starting flowvisor with the configuration stored in DB
If DB unpopulated, laod config using 'fvconfig load config.json'

then i run fvconfig load config.json and it give me the following error:
Could not find /usr/etc/flowvisor/envs.sh: dying...

**Comment by alshabib** [comment]
Did you run sudo make install? Also why are you using such an old version
of FlowVisor?

## 

Ali Al-Shabibi

On May 22, 2013, at 7:49, 09bicsemalam notifications@github.com wrote:

I have installed it but with an error. When I start FV. a message appears:

Starting flowvisor with the configuration stored in DB
If DB unpopulated, laod config using 'fvconfig load config.json'

then i run fvconfig load config.json and it give me the following error:
Could not find /usr/etc/flowvisor/envs.sh: dying...

—
Reply to this email directly or view it on
GitHubhttps://github.com/OPENNETWORKINGLAB/flowvisor/issues/237#issuecomment-18283507
.

**Comment by 09bicsemalam** [comment]
I did sudo make install. Settting fvuser and fvgroup to my username (netforall) in my case.

And about the version im using 0.8. Is this issue somehow relates to the verison??

**Comment by alshabib** [comment]
It should not be related to the version number. Could you send the output of sudo make install?

## 

Ali Al-Shabibi (sent from handheld)
