### ISSUE TITLE
Problems with flowvisor , please help me :( 

### ISSUE THREAD

**Issue by ayoubezzabi** [opennetworkinglab/flowvisor#286]
My problems are as follow :

The first one  :
For the source installation page 
https://github.com/opennetworkinglab/flowvisor/wiki/Installation-from-Source
When i am trying to install the prerequisites

The result is this message 
“ E: Package 'sun-java6-jdk' has no installation candidate “

So then i decided to use another version of  java 

> I used the VM that has been on the  http://sdnhub.org/ website which has  
> java version "1.8.0_60"
> Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
> ## Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
> 
> And from here other problems started ….
> My steps to set flowvisor
> $ git clone git://github.com/OPENNETWORKINGLAB/flowvisor.git
> $ sudo apt-get update
> $ sudo apt-get install ant  build-essential
> $ cd flowvisor && make
> $ INSTALL_ROOT=$PWD/package_root make fvuser=flowvisor fvgroup=flowvisor  install
> // I used the last command because the command “$ make fvuser=flowvisor fvgroup=flowvisor  install “
> doesn`t exist “ //
>  NOW 
> If I try to use flowvisor without run any topology 
> I am facing the following results
> $ sudo fvconfig load /etc/flowvisor/config.json                          // it is OK
> $ sudo killall controller                                      /// to Stop any running OpenFlow controller
> $ sudo /etc/init.d/flowvisor start
> “starting flowvisor with the configuration stored in DB
> If DB unpopulated, load config using 'fvconfig load config.json'”

$ fvctl set-config --enable-topo-ctrl
“Could not reach a FlowVisor RPC server at localhost:8081.
Please check that FlowVisor is running and try again. “
fvctl get-config
/ sometimes the output is  : Could not reach a FlowVisor RPC server at localhost:8081.
Please check that FlowVisor is running and try again.
And sometimes is : 
{
  "enable-topo-ctrl": false, 
  "flood-perm": {
"dpid": "all", 
"slice-name": "fvadmin"
  }, 
  "flow-stats-cache": 30, 
  "flowmod-limit": {
"fvadmin": {
  "any": null
}
  }, 
  "stats-desc": false, 
  "track-flows": false
}

And for list-slices
$ fvctl list-slices
the result is  
Configured slices:
fvadmin         --> enabled
and sometimes the result is : Could not reach a FlowVisor RPC server at localhost:8081
and I got the first result by using fvctl-xml command 
// note : when using fvctl-xml sometimes the result is :
“ [Fatal Error] :1:1: Content is not allowed in prolog.
error: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
//////

If I want to create Slice it is created successfully
but it is not shown
Configured slices:
fvadmin         --> enabled
now if turn on my topology in onother terminal 
so in flow visor terminal
$ fvctl list-slices
“Could not reach a FlowVisor RPC server at localhost:8081.
Please check that FlowVisor is running and try again.”
fvctl-xml --url=https://localhost:8081  listSlices
the result is : 
“error: java.net.ConnectException: Connection refused “

The same results if I turn on the mininet topology before starting Flowvisor ….

> > > And I read in the installation source “FlowVisor has been tested with Java 6. Other versions of Java are, while they may work, are unsupported and untested. FlowVisor runs best on the SUN or Oracle JDK, other JDKs will work but you may be dropping performance”
> > > So I have decided to use Oracle JDK 6
> > > $ sudo apt-get install build-essential oracle-java6-installer ant eclipse
> > > ..
> > > Then I did the following steps
> > > ubuntu@sdnhubvm:~[19:43]$ sudo update-alternatives --config java 
> > > There are 3 choices for the alternative java (providing /usr/bin/java).

0            /usr/lib/jvm/java-6-oracle/jre/bin/java          1075      auto mode ///

///\* 1            /usr/lib/jvm/java-6-oracle/jre/bin/java          1075      manual mode
  ///2            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode
  ////3            /usr/lib/jvm/java-8-oracle/jre/bin/java          1074      manual mode
///
Press enter to keep the current choice[*], or type selection number: 
ubuntu@sdnhubvm:~[19:43]$ java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
ubuntu@sdnhubvm:~[19:43]$

And for taking precaution
I removed and reinstalled Flowvisor
….
Now the error is:
ubuntu@sdnhubvm:~[20:16]$ sudo fvconfig load /etc/flowvisor/config.jsonException in thread "main" java.lang.UnsupportedClassVersionError: org/flowvisor/config/LoadConfig : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.flowvisor.config.LoadConfig.  Program will exit.
ubuntu@sdnhubvm:~[20:16]$

even when I used the VM that you are used in your tutorial
https://openflow.stanford.edu/display/ONL/Flowvisor

the result  is :
“error: java.net.ConnectException: Connection refused “

Help me!!!!! 
I'm in real big trouble .

**Comment by ayoubezzabi** [comment]
@alshabib

**Comment by ayoubezzabi** [comment]
@billsnow @bocon13 @LucaPrete @leenheer @suibin-onlab

**Comment by MoTKing0** [comment]
I think you can run flowvisor on ubuntu14.04 and install the openjdk-6-jdk :)
