### ISSUE TITLE
Bad Out port issue

### ISSUE THREAD

**Issue by priyathamganta** [opennetworkinglab/flowvisor#292]
Hi everyone,

I have a custom topology with 3 switches and 4 hosts as shown in the attached script. I wanted to create 2 slices -  video and non -video similar to that in [Flowvisor exercise](https://github.com/onstutorial/onstutorial/wiki/Flowvisor-Exercise) but with different topology. I'm getting bad out port error as in the attached screenshot and the hosts are not able to ping each other.
I'm using beacon controllers running on ports 10001 and 10002 as in the flowvisor example.
Can anyone troubleshoot it?
![error](https://user-images.githubusercontent.com/47489106/66292037-22ead880-e898-11e9-8657-195037c374db.JPG)
![links](https://user-images.githubusercontent.com/47489106/66292038-22ead880-e898-11e9-8ccd-c15722a8645f.JPG)
![rules](https://user-images.githubusercontent.com/47489106/66292039-22ead880-e898-11e9-841c-a8d90fd2a9af.JPG)
![topo](https://user-images.githubusercontent.com/47489106/66292041-23836f00-e898-11e9-9a6f-54cc43c63c80.JPG)

**Comment by Multhree** [comment]
Hi, when I start FlowVisor wiht the command```flowvisor /etc/flowvisor/config.json```, I encounted a problem
```
Starting FlowVisor
org.flowvisor.config.ConfigError: Missing configuration for flowvisor base parameters
	at org.flowvisor.config.FVConfig.readFromFile(FVConfig.java:107)
	at org.flowvisor.FlowVisor.main(FlowVisor.java:225)
--- Setting logging level to NOTE
respawning too fast -- DYING
```
Do you know how to solve it?

**Comment by Multhree** [comment]
Hi, when I start FlowVisor wiht the commandflowvisor /etc/flowvisor/config.json, I encounted a problem
```
Starting FlowVisor
--- Setting logging level to NOTE
2019-10-24 12:08:32.887:INFO::Logging to StdErrLog::DEBUG=false via org.eclipse.jetty.util.log.StdErrLog
2019-10-24 12:08:32.904:INFO::jetty-7.0.2.v20100331
2019-10-24 12:08:33.270:INFO::Started SslSelectChannelConnector@0.0.0.0:8081
Startup failed : null
```
Do you know how to solve it?
