### ISSUE TITLE
fvconfig chpasswd doesn't work

### ISSUE THREAD

**Issue by jbsbbn** [opennetworkinglab/flowvisor#82]
This was https://openflow.stanford.edu/bugs/browse/FLOWVISOR-185, and was closed as fixed, but I tried it in 0.8.6 just now, and got an error:

```
[12:30:51] jbs@uxmal:/home/jbs
+$ sudo -u flowvisor fvconfig chpasswd /etc/flowvisor/config.json fvadmin
Enter password for account 'fvadmin' on the flowvisor:
Enter password again
Reading config from /etc/flowvisor/config.json
Exception in thread "main" java.lang.RuntimeException: Initialize the DB connection please.
    at org.flowvisor.config.FVConfigurationController.instance(FVConfigurationController.java:20)
    at org.flowvisor.config.FlowvisorImpl.getProxy(FlowvisorImpl.java:702)
    at org.flowvisor.config.FVConfig.readFromFile(FVConfig.java:116)
    at org.flowvisor.api.APIAuth.main(APIAuth.java:194)
```

And it doesn't actually change the password, of course.

(This is supposed to be run when FV is _not_ running, right?)

Two other minor things:
1. The usage message still mentions config.xml:
   
   [12:30:36] jbs@uxmal:/home/jbs
   +$ sudo -u flowvisor fvconfig chpasswd fvadmin
   Usage: APIAuth config.xml sliceName
     change the passwd for a given slice
2. The second "Enter password again" prompt is somewhat ugly, because it doesn't end in a ": " like the previous ones.

**Comment by alshabib** [comment]
Pushed to nightly.
