### ISSUE TITLE
FlowVisor crashed

### ISSUE THREAD

**Issue by jbsbbn** [opennetworkinglab/flowvisor#90]
/var/log/flowvisor/flowvisor-stderr.log says:

```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:810)
    at java.util.HashMap$KeyIterator.next(HashMap.java:845)
    at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1026)
    at org.flowvisor.events.FVEventLoop.doEventLoop(FVEventLoop.java:136)
    at org.flowvisor.FlowVisor.run(FlowVisor.java:186)
    at org.flowvisor.FlowVisor.main(FlowVisor.java:217)
java.net.BindException: Address already in use
    at java.net.PlainSocketImpl.socketBind(Native Method)
    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:353)
    at java.net.ServerSocket.bind(ServerSocket.java:336)
    at java.net.ServerSocket.<init>(ServerSocket.java:202)
    at javax.net.ssl.SSLServerSocket.<init>(SSLServerSocket.java:125)
    at sun.security.ssl.SSLServerSocketImpl.<init>(SSLServerSocketImpl.java:125)
    at sun.security.ssl.SSLServerSocketFactoryImpl.createServerSocket(SSLServerSocketFactoryImpl.java:91)
    at org.flowvisor.api.SSLWebServer.createServerSocket(SSLWebServer.java:35)
    at org.apache.xmlrpc.webserver.WebServer.setupServerSocket(WebServer.java:183)
    at org.apache.xmlrpc.webserver.WebServer.start(WebServer.java:218)
    at org.flowvisor.api.APIServer.spawn(APIServer.java:94)
    at org.flowvisor.FlowVisor.run(FlowVisor.java:165)
    at org.flowvisor.FlowVisor.main(FlowVisor.java:217)
java.lang.RuntimeException: java.net.BindException: Address already in use
    at org.flowvisor.api.SSLWebServer.createServerSocket(SSLWebServer.java:38)
    at org.apache.xmlrpc.webserver.WebServer.setupServerSocket(WebServer.java:183)
    at org.apache.xmlrpc.webserver.WebServer.start(WebServer.java:218)
    at org.flowvisor.api.APIServer.spawn(APIServer.java:94)
    at org.flowvisor.FlowVisor.run(FlowVisor.java:165)
    at org.flowvisor.FlowVisor.main(FlowVisor.java:217)
Caused by: java.net.BindException: Address already in use
    at java.net.PlainSocketImpl.socketBind(Native Method)
    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:353)
    at java.net.ServerSocket.bind(ServerSocket.java:336)
    at java.net.ServerSocket.<init>(ServerSocket.java:202)
    at javax.net.ssl.SSLServerSocket.<init>(SSLServerSocket.java:125)
    at sun.security.ssl.SSLServerSocketImpl.<init>(SSLServerSocketImpl.java:125)
    at sun.security.ssl.SSLServerSocketFactoryImpl.createServerSocket(SSLServerSocketFactoryImpl.java:91)
    at org.flowvisor.api.SSLWebServer.createServerSocket(SSLWebServer.java:35)
    ... 5 more
```

We upgraded to FV 0.8.6 this morning, and started it up at 09:06:10; I started running our standard FOAM auto-approval tests at 09:11:18, which create and delete a bunch of slices.

**Comment by jbsbbn** [comment]
Is there a way to attach a file to an issue? I don't see an obvious one, but I have the output of `sudo egrep -i "nov 12 09.+flowvisor" /var/log/syslog`, which seems like it might be enlightening (but is 4187 lines long).

**Comment by jbsbbn** [comment]
A little more detail: The crash was at 09:22:13, at which point syslog says

```
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR MAIN THREAD DIED!!! 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR ---------------------------- 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR ----- exception in thread Thread[main,5,main]::java.util.ConcurrentModificationException 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR java.util.HashMap$HashIterator.nextEntry(HashMap.java:810) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR java.util.HashMap$KeyIterator.next(HashMap.java:845) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1026) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR org.flowvisor.events.FVEventLoop.doEventLoop(FVEventLoop.java:136) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR org.flowvisor.FlowVisor.run(FlowVisor.java:186) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR org.flowvisor.FlowVisor.main(FlowVisor.java:217) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR ---------------------------- 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR restarting after main thread died 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR FIXME: need to flush old flow entries 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN shutting down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN tearing down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR FIXME: need to flush old flow entries 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN tearing down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR FIXME: need to flush old flow entries 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN shutting down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN tearing down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR FIXME: need to flush old flow entries 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN shutting down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN tearing down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN shutting down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN tearing down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN shutting down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN shutting down 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: ERROR FIXME: need to flush old flow entries 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN Failed to invoke method changeFlowSpace in class org.flowvisor.api.FVUserAPIXMLRPCImpl: null(exception = class java.util.ConcurrentModificationException) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at java.util.HashMap$HashIterator.nextEntry(HashMap.java:810) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at java.util.HashMap$KeyIterator.next(HashMap.java:845) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.flowvisor.config.FVConfigurationController.fireChange(FVConfigurationController.java:50) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.flowvisor.config.FlowSpaceImpl.notify(FlowSpaceImpl.java:448) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.flowvisor.config.FlowSpaceImpl.notifyChange(FlowSpaceImpl.java:289) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at java.lang.reflect.Method.invoke(Method.java:616) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.flowvisor.config.FVConfigProxy.invoke(FVConfigProxy.java:21) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at $Proxy4.notifyChange(Unknown Source) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.flowvisor.api.FVUserAPIXMLRPCImpl.changeFlowSpace(FVUserAPIXMLRPCImpl.java:104) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at java.lang.reflect.Method.invoke(Method.java:616) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.apache.xmlrpc.webserver.Connection.run(Connection.java:208) 
Nov 12 09:22:13 tulum -1>Nov 12 09:22:13 flowvisor: WARN      at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:68) 
Nov 12 09:22:14 tulum -1>Nov 12 09:22:14 flowvisor: INFO initializing poll loop 
Nov 12 09:22:14 tulum -1>Nov 12 09:22:14 flowvisor: INFO JSON service disabled in config (Jetty webserver port == -1) 
Nov 12 09:22:14 tulum -1>Nov 12 09:22:14 flowvisor: INFO Listenning on port 6633 
Nov 12 09:22:14 tulum -1>Nov 12 09:22:14 flowvisor: INFO initializing FlowVisor UserAPI XMLRPC SSL WebServer on port 8080 
Nov 12 09:22:14 tulum -1>Nov 12 09:22:14 flowvisor: FATAL failed to spawn APIServer 
Nov 12 09:22:14 tulum -1>Nov 12 09:22:14 flowvisor: INFO Shutting down config database. 
Nov 12 09:22:14 tulum -1>Nov 12 09:22:14 flowvisor: INFO Shutting down config database. 
```

Let me know if the preceding bit of log would be useful too.
